import "@/app/globals.css";

// import { StacksList } from "./stacks-list";
import { cloudFormation } from "../clients/cloudFormation";
import { DescribeStacksCommand } from "@aws-sdk/client-cloudformation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const stacksResponse = await cloudFormation.send(
  //   new DescribeStacksCommand({})
  // );

  // const stackNames =
  //   stacksResponse.Stacks?.map(({ StackName }) => StackName ?? "") ?? [];

  return (
    <html lang="en">
      <body>
        <main>
          {/* <StacksList stackNames={stackNames} /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
